### ISSUE TITLE
Simple method for iOS? Current package not working ...

### ISSUE THREAD

**Issue by jonmdev** [ne0rrmatrix/MauiPageFullScreen#6]
As I posted here:
https://github.com/dotnet/maui/issues/5478#issuecomment-1742219379

Full screen can be enabled for MAUI in the builder quite easily for Windows and Android with that included code. However I am not aware of any method for iOS that works. I tried installing your package but on build to iPhone XR it is not working, and I cannot find the core basic function of your package for iOS.

Is it possible to write a simple code to add to the Builder like shown in my post for Windows/Android? A simple solution would be nice and it appears you have looked at this function in depth. If anyone knows it I presume you would.

From what I see your solution is just using:

```
                Shell.SetNavBarIsVisible(currentPage, navBarIsVisible);
                NavigationPage.SetHasBackButton(currentPage, backButton);
                NavigationPage.SetBackButtonTitle(currentPage, backButtonTitle);
```

I don't know if this makes apps full screen if you are using a Shell or Navigation Page but I am not and the current method does nothing for the app as a whole (ie. to ensure the app renders under the status bar at the top and under the pull up bar at the bottom).

Thanks for any help.

**Comment by ne0rrmatrix** [comment]
Setting 
```
<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
````
in Info.plist should fix this issue. I forgot to put in the readme
Tested in debug mode as working with above changes. It will work in shell, navigation, or tabbed page. I forgot to include the plist key which is required to adjust the settings I need to for IOS.

The code I am using to set the status bar in IOS is as follows.
```
 UIKit.UIApplication.SharedApplication.SetStatusBarHidden(shouldBeFullScreen, UIKit.UIStatusBarAnimation.Fade);
```
The code is deprecated and I am looking for better solution. It works for now but I need to update it.
```ShouldBeFullScreen``` is a boolean variable true/false.

If this works for you please tell me. If not can you provide more details and an example.
